version: 2.1 

orbs:
  win: circleci/windows@2.2.0

jobs:
  milan: # name of your job
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified

    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run: choco install googlechrome
      - run: npx cypress run --spec cypress\integration\examples\actions.spec.js --browser chrome
workflows:
  build:
    jobs:
      - milan